// Gulf countries first (main audience), then the rest of the world
// alphabetically. Add or remove countries here any time - no other file
// needs to change.
export const COUNTRIES = [
  // Gulf / GCC
  "Kuwait",
  "Saudi Arabia",
  "United Arab Emirates",
  "Qatar",
  "Bahrain",
  "Oman",
  // Rest of the world
  "Afghanistan",
  "Algeria",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bangladesh",
  "Belgium",
  "Brazil",
  "Brunei",
  "Canada",
  "China",
  "Denmark",
  "Egypt",
  "Finland",
  "France",
  "Germany",
  "Greece",
  "Hong Kong",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Italy",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Lebanon",
  "Libya",
  "Malaysia",
  "Maldives",
  "Mauritius",
  "Mexico",
  "Morocco",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nigeria",
  "Norway",
  "Pakistan",
  "Philippines",
  "Poland",
  "Portugal",
  "Russia",
  "Singapore",
  "South Africa",
  "South Korea",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tanzania",
  "Thailand",
  "Tunisia",
  "Turkey",
  "Uganda",
  "Ukraine",
  "United Kingdom",
  "United States",
  "Uzbekistan",
  "Vietnam",
  "Yemen",
  "Other",
];
